export enum FetchActionTypes {
    SAVE_PAGE = "SAVE_PAGE",
    POST_ONETIME_KEYPAIR = "POST_ONETIME_KEYPAIR",
    GET_ELEMENT_BY_XPATH = "GET_ELEMENT_BY_XPATH",
    EXTRACT_TABLES = "EXTRACT_TABLES",
  }